onnx_file: "$(find yopo_planner)/model/yopo.onnx"
engine_file: "$(find yopo_planner)/model/yopo.engine"

odom_topic: "$(arg odom_topic)"
depth_topic: "$(arg depth_topic)"
ctrl_topic: "$(arg ctrl_topic)"

visualize: true
verbose: false
fp16: true

velocity: 6.0
ctrl_dt: 0.02
arrive_distance: 5.0
min_depth: 0.04
max_depth: 20.0
pitch_angle_deg: 0.0
plan_from_reference: false

goal_x: 50.0
goal_y: 0.0
goal_z: 2.0
