FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04

LABEL org.opencontainers.image.authors="zhangrun <1139135655@qq.com>"
LABEL org.opencontainers.image.description="ROS Noetic + CUDA + CUDNN + TensorRT environment"

SHELL ["bash", "-c"]

# modify CUDA_ARCH_BIN according to your GPU architecture
ARG CUDA_ARCH_BIN=7.5

USER root
ARG USE_PROXY=false
ARG BUILD_HTTP_PROXY
ARG BUILD_HTTPS_PROXY
ARG ROS_VERSION=noetic
ARG USE_PROC=8
ARG ENABLE_NEON="OFF"
ENV OPENCV_VERSION=4.5.4
ARG OPENCV3_VERSION=3.4.16
ARG GLOG_VERSION=v0.3.5
ARG CERES_VERSION=2.0.0rc1
ARG VISION_OPENCV_VERSION=1.16.2
ENV FDRONE_WS=/root/Fast-Drone-XI35
ARG NO_PROXY="localhost,127.0.0.1,mirrors.tuna.tsinghua.edu.cn,mirrors.ustc.edu.cn"
ENV http_proxy=${BUILD_HTTP_PROXY} \
    https_proxy=${BUILD_HTTPS_PROXY} \
    HTTP_PROXY=${BUILD_HTTP_PROXY} \
    HTTPS_PROXY=${BUILD_HTTPS_PROXY} \
    no_proxy=${NO_PROXY} \
    NO_PROXY=${NO_PROXY}

# Use Tsinghua University source mirror
RUN printf "%s\n" \
"deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal main restricted universe multiverse" \
"deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-updates main restricted universe multiverse" \
"deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-backports main restricted universe multiverse" \
"deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-security main restricted universe multiverse" \
> /etc/apt/sources.list

# Install some essential tools
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    tzdata \
    wget \
    curl \
    lsb-release \
    git \
    vim \
    pkg-config \
    openssh-server \
    openssh-client \
    net-tools \
    build-essential \
    htop \
    gdb \
    zip \
    unzip \
    libdw-dev \
    libatlas-base-dev \
    libeigen3-dev \
    libglib2.0-dev \
    libyaml-cpp-dev

# ROS
RUN sh -c 'echo "deb http://mirrors.ustc.edu.cn/ros/ubuntu/ `lsb_release -cs` main" > /etc/apt/sources.list.d/ros-latest.list' && \
      apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654 && \
      apt-get update && \
      apt-get install -y  --no-install-recommends \
      ros-${ROS_VERSION}-ros-base \
      ros-${ROS_VERSION}-nav-msgs \
      ros-${ROS_VERSION}-sensor-msgs \
      ros-${ROS_VERSION}-cv-bridge \
      ros-${ROS_VERSION}-rviz \
      ros-${ROS_VERSION}-image-transport-plugins \
      ros-${ROS_VERSION}-pcl-ros \
      ros-${ROS_VERSION}-message-filters \
      ros-${ROS_VERSION}-tf \
      ros-${ROS_VERSION}-catkin \
      ros-${ROS_VERSION}-roslint \
      ros-${ROS_VERSION}-ddynamic-reconfigure \
      ros-${ROS_VERSION}-vrpn \
      ros-${ROS_VERSION}-geometry-msgs \
      ros-${ROS_VERSION}-tf2-ros \
      ros-${ROS_VERSION}-roscpp \
      ros-${ROS_VERSION}-roslaunch \
      ros-${ROS_VERSION}-roslint \
      ros-${ROS_VERSION}-vrpn-client-ros && \
      echo "source /opt/ros/${ROS_VERSION}/setup.bash" >> /root/.bashrc

# Download third-party source dependencies
WORKDIR /tmp
RUN   mkdir -p /tmp/boostdesc_extfiles && \
      for file in boostdesc_bgm.i boostdesc_bgm_bi.i boostdesc_bgm_hd.i \
                  boostdesc_binboost_064.i boostdesc_binboost_128.i boostdesc_binboost_256.i \
                  boostdesc_lbgm.i; do \
          wget -q https://raw.githubusercontent.com/opencv/opencv_3rdparty/contrib_xfeatures2d_boostdesc_20161012/${file} \
               -O /tmp/boostdesc_extfiles/${file}; \
      done && \
      for file in vgg_generated_48.i vgg_generated_64.i vgg_generated_80.i vgg_generated_120.i; do \
          wget -q https://raw.githubusercontent.com/opencv/opencv_3rdparty/contrib_xfeatures2d_vgg_20160317/${file} \
               -O /tmp/boostdesc_extfiles/${file}; \
      done && \
      git clone --depth 1 --branch ${GLOG_VERSION} https://github.com/google/glog.git /tmp/glog && \
      wget -q https://github.com/ceres-solver/ceres-solver/archive/refs/tags/${CERES_VERSION}.zip -O /tmp/ceres-solver.zip && \
      unzip -q /tmp/ceres-solver.zip -d /tmp && \
      rm /tmp/ceres-solver.zip && \
      wget -q https://github.com/ros-perception/vision_opencv/archive/refs/tags/${VISION_OPENCV_VERSION}.zip -O /tmp/vision_opencv.zip && \
      unzip -q /tmp/vision_opencv.zip -d /tmp && \
      mv /tmp/vision_opencv-${VISION_OPENCV_VERSION}/cv_bridge /tmp/cv_bridge${OPENCV_VERSION} && \
      rm -rf /tmp/vision_opencv-${VISION_OPENCV_VERSION} /tmp/vision_opencv.zip && \
      sed -i 's|^project(cv_bridge)$|project(cv_bridge_454)|' /tmp/cv_bridge${OPENCV_VERSION}/CMakeLists.txt && \
      sed -i '/^set(_opencv_version 4)/i set(OpenCV_DIR /usr/local/opencv-4.5.4/lib/cmake/opencv4)' /tmp/cv_bridge${OPENCV_VERSION}/CMakeLists.txt && \
      sed -i 's|<name>cv_bridge</name>|<name>cv_bridge_454</name>|' /tmp/cv_bridge${OPENCV_VERSION}/package.xml

# Install OpenCV4 with CUDA
RUN   git clone --depth 1 --branch ${OPENCV_VERSION} https://github.com/opencv/opencv_contrib.git && \
      cp /tmp/boostdesc_extfiles/*.i ./opencv_contrib/modules/xfeatures2d/src/
RUN   apt-get update && \
      apt-get install -y --no-install-recommends libgtk2.0-dev && \
      wget https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip -O opencv.zip && \
      unzip opencv.zip && \
      rm opencv.zip && \
      cd opencv-${OPENCV_VERSION} && \
      mkdir build && cd build && \
      cmake .. \
            -D CMAKE_BUILD_TYPE=RELEASE \
            -D CMAKE_INSTALL_PREFIX=/usr/local/opencv-${OPENCV_VERSION} \
            -D WITH_CUDA=ON \
            -D WITH_CUDNN=ON \
            -D WITH_CUBLAS=ON \
            -D CUDNN_VERSION='8.9.6' \
            -D CUDNN_INCLUDE_DIR=/usr/include/ \
            -D CUDA_ARCH_BIN=${CUDA_ARCH_BIN} \
            -D CUDA_ARCH_PTX="" \
            -D CUDA_FAST_MATH=ON \
            -D WITH_TBB=ON \
            -D BUILD_opencv_python2=OFF \
            -D BUILD_opencv_python3=ON \
            -D OPENCV_DNN_CUDA=ON \
            -D OPENCV_ENABLE_NONFREE=ON \
            -D OPENCV_EXTRA_MODULES_PATH=/tmp/opencv_contrib/modules \
            -D BUILD_EXAMPLES=OFF \
            -D BUILD_opencv_java=OFF \
            -D BUILD_opencv_python=OFF \
            -D BUILD_TESTS=OFF \
            -D BUILD_PERF_TESTS=OFF \
            -D BUILD_opencv_apps=OFF \
            -D ENABLE_NEON=${ENABLE_NEON} \
            -D EIGEN_INCLUDE_PATH=/usr/include/eigen3 \
            -D WITH_EIGEN=ON \
            -D WITH_IPP=OFF \
            -D WITH_OPENCL=OFF \
            -D PYTHON3_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.8.so \
            -D BUILD_LIST=calib3d,features2d,highgui,dnn,imgproc,imgcodecs,cudev,cudaoptflow,cudaimgproc,cudalegacy,cudaarithm,cudacodec,cudastereo,cudafeatures2d,xfeatures2d,tracking,stereo,aruco,videoio,ccalib && \
      make -j${USE_PROC} && \
      make install

# Build cv_bridge for OpenCV4.5.4
RUN   mkdir -p /root/cv_bridge${OPENCV_VERSION}_ws/src && \
      mv /tmp/cv_bridge${OPENCV_VERSION} /root/cv_bridge${OPENCV_VERSION}_ws/src && \
      /bin/bash -c 'source /opt/ros/${ROS_VERSION}/setup.bash && \
      cd /root/cv_bridge${OPENCV_VERSION}_ws && catkin_make && echo "source /root/cv_bridge${OPENCV_VERSION}_ws/devel/setup.bash" >> /root/.bashrc'

# Install Intel RealSense SDK
WORKDIR /tmp
RUN   apt-get update && \
      apt-get install -y --no-install-recommends ca-certificates curl && \
      install -d -m 0755 /etc/apt/keyrings && \
      curl -fsSL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xFB0B24895113F120" -o /etc/apt/keyrings/librealsense.asc && \
      echo "deb [signed-by=/etc/apt/keyrings/librealsense.asc] https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" > /etc/apt/sources.list.d/librealsense.list && \
      apt-get update && \
      apt-get install -y librealsense2-dev=2.55.1-0~realsense.12422 \
                         librealsense2=2.55.1-0~realsense.12422 \
                         librealsense2-utils=2.55.1-0~realsense.12422 \
                         librealsense2-dbg=2.55.1-0~realsense.12422 \
                         librealsense2-gl=2.55.1-0~realsense.12422 && \
      apt-mark hold librealsense2 librealsense2-dev librealsense2-utils librealsense2-dbg

# Install MAVROS
RUN   apt-get install -y --no-install-recommends ros-${ROS_VERSION}-mavros && \
      cd /opt/ros/${ROS_VERSION}/lib/mavros && \
      ./install_geographiclib_datasets.sh

# Build Glog
RUN   apt-get install -y --no-install-recommends autoconf automake libtool liblapack-dev libsuitesparse-dev libcxsparse3 libgflags-dev libgoogle-glog-dev libgtest-dev && \
      cd /tmp/glog && \
      chmod +x autogen.sh configure && ./autogen.sh && ./configure && \
      make -j${USE_PROC} && make install

# Build Ceres
RUN   cd /tmp/ceres-solver-2.0.0rc1 && mkdir build && cd build && \
      cmake -DCMAKE_BUILD_TYPE=Release -DCUDA=OFF .. && make -j${USE_PROC} && make install && \
      rm -rf ../../ceres-solver-2.0.0rc1

# Install LCM
RUN   cd /tmp && git clone --depth 1 --branch v1.4.0 https://github.com/lcm-proj/lcm && \
      cd lcm && \
      mkdir build && cd build && \
      cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DBUILD_BENCHMARKS=OFF .. && \
      make -j${USE_PROC} && make install

# Install onnxruntime
RUN   apt-get update && \
      apt-get install -y --no-install-recommends python3-pip && \
      /usr/bin/pip3 install onnxruntime -i https://pypi.tuna.tsinghua.edu.cn/simple

# Install dependencies for gscam
RUN   apt-get update && \
      apt-get install -y --no-install-recommends \
      gstreamer1.0-tools \
      libgstreamer1.0-dev \
      libgstreamer-plugins-base1.0-dev \
      libgstreamer-plugins-good1.0-dev \
      ros-${ROS_VERSION}-camera-calibration-parsers \
      ros-${ROS_VERSION}-camera-info-manager

# Build OpenCV3
RUN   cd /tmp && \
      wget -q https://github.com/opencv/opencv/archive/refs/tags/${OPENCV3_VERSION}.zip -O opencv-${OPENCV3_VERSION}.zip && \
      wget -q https://github.com/opencv/opencv_contrib/archive/refs/tags/${OPENCV3_VERSION}.zip -O opencv_contrib-${OPENCV3_VERSION}.zip && \
      unzip -q opencv-${OPENCV3_VERSION}.zip && \
      unzip -q opencv_contrib-${OPENCV3_VERSION}.zip && \
      rm opencv-${OPENCV3_VERSION}.zip opencv_contrib-${OPENCV3_VERSION}.zip && \
      cd /tmp/opencv-${OPENCV3_VERSION} && mkdir build && cd build && \
      cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local/opencv-${OPENCV3_VERSION} \
      -D OPENCV_EXTRA_MODULES_PATH=/tmp/opencv_contrib-${OPENCV3_VERSION}/modules \
      -D WITH_CUDA=ON \
      -D CUDA_ARCH_BIN=${CUDA_ARCH_BIN} \
      -D CUDNN_VERSION='8.9.6' \
      -D CUDNN_INCLUDE_DIR=/usr/include/ \
      -D CUDA_ARCH_PTX="" \
      -D ENABLE_FAST_MATH=ON \
      -D CUDA_FAST_MATH=ON \
      -D WITH_CUBLAS=ON \
      -D WITH_LIBV4L=ON \
      -D WITH_GSTREAMER=ON \
      -D WITH_GSTREAMER_0_10=OFF \
      -D WITH_QT=ON \
      -D WITH_OPENGL=ON \
      -D CUDA_NVCC_FLAGS="--expt-relaxed-constexpr" \
      -D WITH_TBB=ON \
      .. && \
      make -j${USE_PROC} && \
      make install

# TensorRT
WORKDIR  /tmp
COPY     ./TensorRT-8.6.1.6.Linux.x86_64-gnu.cuda-11.8.tar.gz /tmp
RUN      mkdir -p /usr/local/TensorRT-8.6.1.6 && \
         tar -xzf TensorRT-8.6.1.6.Linux.x86_64-gnu.cuda-11.8.tar.gz -C /usr/local/TensorRT-8.6.1.6 --strip-components=1 && \
         ln -sfn /usr/local/TensorRT-8.6.1.6 /usr/local/tensorrt && \
         ln -sfn /usr/local/TensorRT-8.6.1.6/include /usr/local/include/tensorrt && \
         echo 'export LD_LIBRARY_PATH=/usr/local/tensorrt/lib:$LD_LIBRARY_PATH' >> /root/.bashrc && \
         cp /usr/local/tensorrt/bin/trtexec /bin/trtexec && \
         rm -f /tmp/TensorRT-8.6.1.6.Linux.x86_64-gnu.cuda-11.8.tar.gz

# Other Config
RUN   /usr/bin/pip3 install scikit-image

# Config SSH
RUN  mkdir /var/run/sshd && \
echo 'root:123456' | chpasswd && \
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
EXPOSE 22

# Clean up all temp files
RUN apt-get clean && rm -rf  /var/tmp/* /var/lib/apt/lists/* /var/cache/apt/* /tmp/*
ENV http_proxy= \
    https_proxy= \
    HTTP_PROXY= \
    HTTPS_PROXY=
WORKDIR /root
