ARG JETSON_BASE_IMAGE=fastdronexi35:orin_base_35.3.1
FROM ${JETSON_BASE_IMAGE}

ARG USE_PROXY=false
ARG BUILD_HTTP_PROXY
ARG BUILD_HTTPS_PROXY
ARG ROS_VERSION=noetic
ENV OPENCV_VERSION=4.5.4
ENV FDRONE_WS=/root/Fast-Drone-XI35

SHELL ["bash", "-c", "-l"]

# Clone Fast-Drone-XI35
RUN  git config --global http.lowSpeedLimit 0 && \
     git config --global http.lowSpeedTime 999999 && \
     git config --global http.postBuffer 1024288000 && \
     if [ "$USE_PROXY" = "true" ]; then \
       export http_proxy="${BUILD_HTTP_PROXY}" https_proxy="${BUILD_HTTPS_PROXY}" \
              HTTP_PROXY="${BUILD_HTTP_PROXY}" HTTPS_PROXY="${BUILD_HTTPS_PROXY}"; \
     fi && \
     cd /root && git clone --depth 1 --branch board https://github.com/HIT-K1928-LAB/Fast-Drone-XI35.git
WORKDIR ${FDRONE_WS}

# container init
COPY ./container_init.sh /
COPY ./daemon /daemon
RUN  chmod +x /container_init.sh
ENTRYPOINT ["/bin/bash", "/container_init.sh"]
